Program Running(Decent template). Need to fix Error.
Error: When I fill out entry fields and press the run button, I get error:  '<' not supported between instances of 'str' and 'float'